
name: Compile-Tex

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs: 
  compile:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2023.1
    name: Compile tex CV
    steps:
      - name: Install git
        run: |
            apk update && apk upgrade
            apk --no-cache add git
            git --version
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Build Latex
        run: pdflatex  CV.tex
      
      - name: Config git
        run: |
            git config --global --add safe.directory $(realpath .)
            git checkout main
            
      - uses: EndBug/add-and-commit@v9
        with:
          add: CV.pdf
          author_name: Latex Compiler
          author_email: noreplay@users.noreply.github.com
          message: Automatically updating the CV
      