
name: Compile-Tex

on:
  push:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "say_hello"
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Ls
        run: ls -al
      - name: PWD
        run: pwd
      
  compile:
    runs-on: ubuntu-latest
    name: Compile tex CV
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker build -t local -f  Dockerfile .
      - name: Run tests
        run: docker run -v ${PWD}:/working_dir local
    
      - name: Commit changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add CV.pdf
          git commit -am "Auto updating CV"
          git push

      # - name: config
      #   run: |
      #     git config --local user.name "latex_compiler"
      # - name: check for changes
      #   run: git status
      # - name: stage changed files
      #   run: git add .
      # - name: commit changed files
      #   run: git commit -m "Auto updating CV"
      # - name: fetch from master
      #   run: git fetch origin master
      # - name: push code to master
      #   run: git push origin HEAD:master
      