
name: Compile-Tex

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs: 
  compile:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2023.1
    name: Compile tex CV
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build Latex
        run: pdflatex  CV.tex
      # - name: Run tests
      #   run: docker run -v ${PWD}:/working_dir local
      - name: Check current directory
        run: |
            pwd
            ls -la
      - name: Commit changes
        working-directory: ${{ github.workspace }}
        run: |
          apk --no-cache add sudo
          
          sudo apk update & sudo  apk upgrade
          sudo  apk --no-cache add git
          # chown -R root:root .
          sudo  git config --global --add safe.directory $(realpath .)
          sudo  git config --global user.name 'Latex Compiler'
          sudo  git config --global user.email 'noreplay@users.noreply.github.com'
          sudo git add CV.pdf
          sudo git commit -am "Auto updating CV"
          sudo git push origin HEAD:main
