
name: Compile-Tex

on:
  push:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "say_hello"
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo Hello World
      - name: Say Goodbye
        run: |
          echo Job Finished.
          echo Goodbye!
  compile:
    runs-on: ubuntu-latest
    name: Compile tex CV
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker build -t local < ./Dockerfile
      - name: Run tests
        run: docker run -it  local
      