
name: Compile-Tex

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs: 
  compile:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2023.1
    name: Compile tex CV
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Latex
        run: pdflatex  CV.tex
      # - name: Run tests
      #   run: docker run -v ${PWD}:/working_dir local
      - name: Check current directory
        run: |
            pwd
            ls -la
      - name: Commit changes
        working-directory: ${{ github.workspace }}
        run: |
          apk --no-cache add git
          ls -la
          git config --global user.name 'Latex Compiler'
          git config --global user.email 'noreplay@users.noreply.github.com'
          git add CV.pdf
          git commit -am "Auto updating CV"
          git push
