name: Compile-Tex-CV

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs: 
  compile:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2023.1
    name: Compile multilingual CV
    steps:
      - name: Install git and fonts
        run: |
            apk update && apk upgrade
            apk --no-cache add git
            apk --no-cache add font-noto font-noto-cjk
            fc-cache -f
            git --version
      
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Build English CV
        run: xelatex cv_en.tex
      
      - name: Build Russian CV
        run: xelatex cv_ru.tex
            
      - name: Config git
        run: |
            git config --global --add safe.directory $(realpath .)
            git checkout main
            
      - uses: EndBug/add-and-commit@v9
        with:
          add: |
            cv_en.pdf
            cv_ru.pdf
          author_name: LaTeX Compiler
          author_email: noreply@github.com
          message: Automatically updating the multilingual CV