
name: Compile-Tex

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs: 
  compile:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2023.1
    name: Compile tex CV
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build Latex
        run: pdflatex  CV.tex
      # - name: Run tests
      #   run: docker run -v ${PWD}:/working_dir local
      - name: Install git
        run: |
            apk upgrade --no-cache
            apk --no-cache add git
            git config --global --add safe.directory $(realpath .)
            
      - uses: EndBug/add-and-commit@v9
        with:
          add: CV.pdf
          author_name: Latex Compiler
          author_email: noreplay@users.noreply.github.com
          message: Automatically updating the CV
      